### ISSUE TITLE
Refactor to use curl

### ISSUE THREAD

**Issue by rcross** [ibaaj/Regex101.com-offline-app#3]
Considering that CURL is a much more ubiquitous command compared to wget, why not refactor the code to use that?

**Comment by ibaaj** [comment]
it's easier with wget because it can download recursively (-recursive option).
[#1](http://apple.stackexchange.com/questions/100570/getting-files-all-at-once-from-a-web-page-using-curl)
[#3](http://unix.stackexchange.com/questions/47434/what-is-the-difference-between-curl-and-wget)
[#3](http://stackoverflow.com/questions/273743/using-wget-to-recursively-fetch-a-directory-with-arbitrary-files-in-it)

**Comment by rcross** [comment]
Yea, i noticed that after the fact. 

I did see that you could make the script a bit simpler though; 
`wget --mirror -p --convert-links -P /tmp/regex http://regex101.com`
